ALTER TABLE address ADD user_id INT;

ALTER TABLE address ADD created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE address ADD updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE address ADD CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users(user_id);

SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME = 'users' AND COLUMN_NAME = 'address_id';

ALTER TABLE users DROP FOREIGN KEY users_ibfk_1;

ALTER TABLE users DROP COLUMN address_id;